add_newline = false
format = "$directory$git_branch$git_status$nodejs$python$dotnet$java$rust$cmd_duration$line_break$character"
palette = "tokyo_night"

[palettes.tokyo_night]
background = "#1a1b26"
foreground = "#a9b1d6"
comment = "#565f89"
red = "#f7768e"
orange = "#ff9e64"
yellow = "#e0af68"
green = "#9ece6a"
cyan = "#7dcfff"
blue = "#7aa2f7"
magenta = "#bb9af7"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold blue"

[git_branch]
symbol = "git:"
style = "bold magenta"

[git_status]
style = "yellow"

[nodejs]
symbol = "node "
style = "green"

[python]
symbol = "py "
format = 'via [${symbol}${version}( \($virtualenv\))]($style) '
style = "yellow"

[dotnet]
symbol = ".NET "
style = "magenta"

[java]
symbol = "java "
style = "red"

[rust]
symbol = "rust "
style = "orange"

[cmd_duration]
min_time = 2000
style = "comment"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
